{% set name = "Grouper" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/Grouper/archive/v{{ version }}.tar.gz
  sha256: b6fddeb6bad6eb758a86e00ee5091b2f6634221515fef04c0b7c021b9de8a8db

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  build: 
    - python                                 
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make 
    - librdkit <=2024.09.3
    - rdkit
    - librdkit-dev
    - libboost-devel
    - nauty
    - llvm-openmp
  host:
    - python
    - scikit-build-core
    - pip
    - pybind11
    - nlohmann_json
    - librdkit-dev
    - rdkit
  run:
    - python
    - libboost-python-devel
    - librdkit
    - libpq
    - rdkit
    - eigen
    - pybind11
    - nauty
    - jupyter
    - seaborn
    - cairosvg
    - pytorch
    - python-igraph
    - dash
    - dash_cytoscape
    - scikit-learn
    - llvm-openmp

test:
  imports:
    - Grouper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mosdef-hub/Grouper
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A software package for creating and manipulating graphs of molecular groups.

  description: |
    Grouper is a package for working with molecular graphs, breaking them into component 
    subgraphs. This procedure works hand in hand for functional group fragmentation and
    exhaustive generation of large molecular spaces, useful for ML data-based screening 
    and high-throughput chemical search.
  dev_url: https://github.com/mosdef-hub/Grouper


extra:
  recipe-maintainers:
    - CalCraven
    - kierannp
    - chrisjonesBSU
